# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2QUOyRyxt0MSVFSYXrNyrn1D2UMsEPz
"""

def summarize_text(text, num_sentences=2):
    # Split text into sentences
    sentences = text.split('. ')

    # Rank sentences by their length (longer sentences are prioritized as they often contain more information)
    sorted_sentences = sorted(sentences, key=len, reverse=True)

    # Select the top N sentences
    summary = '. '.join(sorted_sentences[:num_sentences])

    return summary

# Example usage
if __name__ == "__main__":
    input_text = """
    Natural language processing (NLP) is a subfield of linguistics, computer science, and artificial intelligence.
    It deals with the interaction between computers and human language, focusing on how to program computers to process and analyze large amounts of natural language data.
    The goal is to enable computers to understand, interpret, and generate human languages in a valuable way.
    Applications of NLP include language translation, sentiment analysis, and chatbots.
    """
    print("Summary:")
    print(summarize_text(input_text, num_sentences=2))